# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: kanishkarathore1603@gmail.com
author_name: kanishkarathore
contract_name: carbon_engine
deployment_language: python
preset_name: starter
project_name: carbon_engine

